### ISSUE TITLE
Typo in the docs

### ISSUE THREAD

**Issue by steffahn** [danielhenrymantilla/nougat.rs#6]
Under [“some historical context”](https://docs.rs/nougat/0.1.0/nougat/#some-historical-context)
> 2. 2021/03/08: [I officially mention the workaround for “late/for-quantifying where T : 'lt” clauses thanks implicit bounds on types such as &'lt T](https://users.rust-lang.org/t/how-to-end-borrow-in-this-code/72719/2?u=yandros).

The date should be 2022/03/08

**Comment by danielhenrymantilla** [comment]
Ah damn I misread URLO dates 😅. Will fix it when I'm back to the computer. Btw, can you dig up the earliest instances of your own research on hrtb and implicit bounds? I'd like to add it as well; I think it's interesting to see the path made from discovering a language quirk to tricks being known by forum regulars, and up to it becoming knowledge spread across most hrtb-acquainted) rustaceans 😄

**Comment by steffahn** [comment]
I don’t quite remember the details here, but let me piece things together from what’s recorded in my public postings.

I looked into HRTBs and implied bounds a lot around the time I ran into soundness issues related to those topics…  [looking through those](https://github.com/rust-lang/rust/issues?q=is%3Aissue+author%3Asteffahn+label%3AI-unsound+label%3AA-lifetimes) the time-frame for that is April 2021. I don’t remember how familiar I was with implied bounds prior to that, I certainly had some understanding by [April 26th](https://github.com/rust-lang/rust/issues/84591).

Regarding using them in GATs, quinedot had [listed](https://users.rust-lang.org/t/how-to-become-a-rust-ninja/64085/17) some posts of mine on URLO; as far as I remember, I came up with the idea to use a generic parameter for its implied bounds myself; I’m not sure but I might have “re-invented” the idea to use HRTBs to emulate GATs, too, instead of reading about it somewhere else. Hard to remember such things, though. I think my general approach was: lots of interacting with URLO questions for inspiration as to what parts of Rust to play around with; when something seems weird/interesting play around with toy examples until I get an intuitive understanding of it. (I think that’s where e.g. my knowledge about implied bounds came from.)

In any case… going by those posts linked by quinedot, by some time up to [June 20th, 2021](https://users.rust-lang.org/t/how-do-i-fix-this-lifetime-error/61308/5?u=steffahn) I was apparently aware of how to do the whole GAT-emulation thing including the “hack” for the outlives bound; though the far more straightforward/readable (and thus worth linking) post of mine on this is [this one from one month later](https://users.rust-lang.org/t/lifetime-conflicting-requirements/64070/4).

**Comment by Kestrer** [comment]
That would mean that I _was_ actually the first to discover this, because [my Discord post](https://discordapp.com/channels/273534239310479360/592856094527848449/842872536618106900) happened on 2021-05-14. But I don’t think steffahn uses Discord, so either it must have somehow percolated over time into URLO or steffahn independently discovered the same thing.

**Comment by danielhenrymantilla** [comment]
It is quite typical to have independent findings of the same thing, since it means the "info was around and fertile enough to give life to this new idea" 😄. I know that I myself saw Kestrer's discord post and it resonated with some experimentation of my own but I had never had the idea to apply it like that, so the moment I saw it I added it to my own mental "trick list". I'm gonna give credit to you two for the findings, then 🙂
